# Generated by Django 4.0.4 on 2022-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coin_type', models.CharField(choices=[('BTC', 'B.T.C'), ('ETH', 'E.T.H')], max_length=5)),
            ],
        ),
    ]
