# Generated by Django 4.0.4 on 2022-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket_api', '0002_rename_name_wallet_coin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='coin_type',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'eth')], max_length=3),
        ),
    ]
